### PR TITLE
VTM rebranding

### PR DESCRIPTION
**Pull request by mediaminister**
Preparing for the VTM rebranding that will be launched on August 31

### CODE REVIEW

**Comment by dagwieers** [comment]
The launch is on monday 31 august, so I expect this to take place the entire day.
We will have to check sunday night/monday morning, when they have switched it on in the VTM GO app.

We may want to involve @basrieter and @enen92 to ensure the prepared changes are already fine in advance, and any required fixes are vetted too and pushed as soon as possible on the day itself.

The 24h frequency will ensure we miss primetime for the majority of users anyway. So better tell our users to refresh the Kodi repositories manually as soon as it becomes available.

**Comment by enen92** [comment]
I'd say to keep the rebranding changes localized and not part of a big changeset (i.e. a major release). That way chances of speeding up the merging process are greater.

**Comment by michaelarnauts** [comment]
That's okay. We just had a release. I think there is only a bigfix for Windows paths that has been merged since the release.

**Comment by michaelarnauts** [comment]
@dagwieers unless they make major changes, a release is not strictly required to keep on watching live TV since this PR: https://github.com/add-ons/plugin.video.vtm.go/pull/179

**Comment by dagwieers** [comment]
> @dagwieers unless they make major changes, a release is not strictly required to keep on watching live TV since this PR: #179

I agree, but we won't know for sure until 31/8 what will be impacted. So we might as well expect the worst 😬

**Comment by mediaminister** [comment]
Please test, I think it's safe to release this.

**Comment by michaelarnauts** [comment]
Just tested this, and this seems to work fine!

The current release also keeps working, but there is no TV Guide to browse in VTM2, VTM3 and VTM4. It does show the current running program.

**Pull request merged**
