### PR TITLE
Prepare for v1.1.5

### PR DESCRIPTION
**Pull request by mediaminister**

### CODE REVIEW

**Comment by mediaminister** [comment]
Unit tests ran fine: https://github.com/mediaminister/plugin.video.vtm.go/runs/1285309964

```
2020-10-21T07:09:28.5471130Z Ran 27 tests in 27.492s
2020-10-21T07:09:28.5471335Z 
2020-10-21T07:09:28.5471549Z OK
```

**Comment by michaelarnauts** [comment]
> Testing master branch in VM's now:
> 
> * Add to mylist is broken

It seems that even when the `API_ENDPOINT` is prefixed, it still doesn't work. The DELETE returns 204, but the actual listing doesn't change. The Android app uses the new endpoints for this, maybe this is the reason, and the old API isn't syncing anymore with the new one?

**Comment by mediaminister** [comment]
The api has changed, post requests are used now, but I guess there is some kind of authentication needed now:
https://vtm.be/vtmgo/userData/myList/program/343858f4-b704-452e-a1bc-e3a1e765ce9f/add
https://vtm.be/vtmgo/userData/myList/program/343858f4-b704-452e-a1bc-e3a1e765ce9f/remove

**Comment by michaelarnauts** [comment]
> The api has changed, post requests are used now, but I guess there is some kind of authentication needed now:
> https://vtm.be/vtmgo/userData/myList/program/343858f4-b704-452e-a1bc-e3a1e765ce9f/add
> https://vtm.be/vtmgo/userData/myList/program/343858f4-b704-452e-a1bc-e3a1e765ce9f/remove

This is using the website API. I think we better fix this by using the underlying API (`https://lfvp-api.dpgmedia.net`) like you did in your PR, but maybe not for the streams, se we can keep on using the current way of playing the advertisements?

**Comment by mediaminister** [comment]
Okay, this is possible. I'll make a PR.

**Comment by michaelarnauts** [comment]
> Okay, this is possible. I'll make a PR.

Hold on, the fix is easy. We weren't passing our tokens to the DELETE and PUT call.

**Comment by michaelarnauts** [comment]
See https://github.com/add-ons/plugin.video.vtm.go/pull/227

**Comment by mediaminister** [comment]
That was it, it works again.

**Pull request merged**
