### PR TITLE
Rework to use new authentication, remove broken features.

### PR DESCRIPTION
**Pull request by michaelarnauts**
Changes:
* Implemented new login flow
* Removed catalog features (since the endpoint has been removed)
* Removed library support (again, the catalog endpoint has been removed)
* Removed metadata caching (again, the catalog endpoint has been removed)
* Always uses the main profile (kids can be selected in the main menu)

# Update 2021-11-27
[plugin.video.vtm.go-1.3+matrix.1-rework-e3ee17c.zip](https://github.com/add-ons/plugin.video.vtm.go/files/7612013/plugin.video.vtm.go-1.3%2Bmatrix.1-rework-e3ee17c.zip)
[plugin.video.vtm.go-1.3-rework-e3ee17c.zip](https://github.com/add-ons/plugin.video.vtm.go/files/7612014/plugin.video.vtm.go-1.3-rework-e3ee17c.zip)

### CODE REVIEW

**Comment by michaelarnauts** [comment]
For some brave souls who want to try this out:

[plugin.video.vtm.go-1.2.12+matrix.1+matrix.1-rework-6052cd0.zip](https://github.com/add-ons/plugin.video.vtm.go/files/7605227/plugin.video.vtm.go-1.2.12%2Bmatrix.1%2Bmatrix.1-rework-6052cd0.zip)

[plugin.video.vtm.go-1.2.12+matrix.1-rework-6052cd0.zip](https://github.com/add-ons/plugin.video.vtm.go/files/7605228/plugin.video.vtm.go-1.2.12%2Bmatrix.1-rework-6052cd0.zip)

**Comment by Bart80-1** [comment]
I tested this on Linux (Mint 20.2) with Kodi 19 + RPi4 with LibreElec 10.
Login works nicely, but after the code is entered in the VTM-Go website and the dialogbox in Kodi is answered with "Yes refresh", the dialogsbox keeps reappearing. Clicking "No" solves it.
A-Z is indeed removed (makes sense if VTM-Go dropped it). 
Subtitles worked again! At least under Linux. 
On LibreElec10 i got it working for Timeless episide 2x08 "The day Reagan was shot" and Aspe S6E06 ("De Valkenier"). S6E13 ("De architect (deel 2)") did not display the subtitles - however, it works under Linux.

Anything else in particular you need testing for?

**Comment by michaelarnauts** [comment]
> I tested this on Linux (Mint 20.2) with Kodi 19 + RPi4 with LibreElec 10. Login works nicely, but after the code is entered in the VTM-Go website and the dialogbox in Kodi is answered with "Yes refresh", the dialogsbox keeps reappearing. Clicking "No" solves it. A-Z is indeed removed (makes sense if VTM-Go dropped it). Subtitles worked again! At least under Linux. On LibreElec10 i got it working for Timeless episide 2x08 "The day Reagan was shot" and Aspe S6E06 ("De Valkenier"). S6E13 ("De architect (deel 2)") did not display the subtitles - however, it works under Linux.
> 
> Anything else in particular you need testing for?

Cool. Thanks for testing. I haven't looked at the search, and I didn't look at the recommendation menu's.

Odd that the login behaved like that. It should redirect to the main menu after selecting refresh, but I have only minimally tested it, so it can be improved a lot.

**Comment by cometoluc** [comment]
Hello,

i tried to use plugin.video.vtm.go-1.2.12+matrix.1-rework-8563c0d.zip and also 
plugin.video.vtm.go-1.2.12-rework-8563c0d.zip, but 

i work in windows 7 32 pc with latest kodi

**Comment by michaelarnauts** [comment]
I've uploaded new zips at the PR start. See https://github.com/add-ons/plugin.video.vtm.go/pull/311#issue-789113298

**Comment by Bart80-1** [comment]
I noticed that I could no longer use the first version of the addon.
Error log here: [https://paste.kodi.tv/leparapoqu](https://paste.kodi.tv/leparapoqu)
Error is 
`Error Contents: 401 Client Error: Unauthorized for url:
https://lfvp-api.dpgmedia.net/vtmgo/tokens .`

Is it possible that the token expires after 24 hours? That is more or less the time that has run between my first tests and now...

I installed the newer version. With the new one I was succesfully able to remove the authentication tokens and re-login (this didn't work with the first one).
After Sunday evening I'll be able to tell you if the token expiry problem after 24 hour still persists ;)

**Comment by michaelarnauts** [comment]
> I noticed that I could no longer use the first version of the addon. Error log here: https://paste.kodi.tv/leparapoqu Error is `Error Contents: 401 Client Error: Unauthorized for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens .`
> 
> Is it possible that the token expires after 24 hours? That is more or less the time that has run between my first tests and now...
> 
> I installed the newer version. With the new one I was succesfully able to remove the authentication tokens and re-login (this didn't work with the first one). After Sunday evening I'll be able to tell you if the token expiry problem after 24 hour still persists ;)

That was indeed an issue with the first version, and should be fixed in this one. But it's good to have this tested on more systems :) Thanks!

**Comment by cometoluc** [comment]
Hello,

i did the addon and vtmgo seemd to work again, but today i found out that i can not see the live channels

i work on windows7 32 pc with latest kodi

**Comment by frankdpGH** [comment]
Hi Michael,  tested plugin.video.vtm.go-1.3+matrix.1-rework-e3ee17c.zip on a Android box (Android 9 ARM 64-bit). 
Authentication method works perfect. OK with no Lib support (better than having all these error messages).
Subtitles are working again for VOD starting from the addon guide.
Subtitles not working when starting from EPG IPTV manager (had this issue already before,  and using work around )(https://github.com/add-ons/plugin.video.vtm.go/issues/308#issuecomment-980709965)
Attach a test log for subtitles :  
19:07 starting movie MIB from VTMGO addon at 19:12 Subtitles are visible and working
19:14 starting movie MIB form EPG / IPTV mgr at 19:18 no subtitles working
[kodi.log](https://github.com/add-ons/plugin.video.vtm.go/files/7620410/kodi.log)

**Comment by badoneti** [comment]
Accidentally found this update and tried it out. Worked well on x86-64, LibreElec 10.0.1 Kodi 19.3
Both the authentication mechanism and subtitles work again, thanks a lot for the efforts 👍 !
A pitty that the library integration had to be dropped. A matter of priorities as well I assume.

**Comment by michaelarnauts** [comment]
> Accidentally found this update and tried it out. Worked well on x86-64, LibreElec 10.0.1 Kodi 19.3 Both the authentication mechanism and subtitles work again, thanks a lot for the efforts 👍 ! A pitty that the library integration had to be dropped. A matter of priorities as well I assume.

I need to some more testing, and will probably be able to release this soon.

Regarding the library Integration, did you actually buse this? My experience with it was that it didn't always correctly pick up new episodes, so I wasn't sure if it was actually being used by users.

**Comment by badoneti** [comment]
> Regarding the library Integration, did you actually buse this? My experience with it was that it didn't always correctly pick up new episodes, so I wasn't sure if it was actually being used by users.

I did liked it a lot until it got broken: see #280

**Pull request merged**
