### PR TITLE
Fix log level in Kodi 19

### PR DESCRIPTION
**Pull request by mediaminister**
This fixes https://github.com/add-ons/plugin.video.vtm.go/issues/193 when https://github.com/xbmc/xbmc/pull/18346 will get merged.

### CODE REVIEW

**Comment by michaelarnauts** [comment]
PR in Kodi has been merged, looking at this PR, I guess we better define the info_level once outside the emit method.

**Comment by mediaminister** [comment]
Okay, `info_level` is defined in the `__init__` method now.

**Comment by michaelarnauts** [comment]
@mediaminister if I merge this, you'll need to change your kodiutils branch again, so maybe it's better to just make this change in your kodiutils branch, and then we close this?

**Comment by mediaminister** [comment]
Okay, I added fix this to https://github.com/add-ons/plugin.video.vtm.go/pull/214

**Pull request closed without merging**
