### PR TITLE
Update to version 13 API

### PR DESCRIPTION
**Pull request by mediaminister**

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Awesome! Thanks @mediaminister!

**Comment by michaelarnauts** [comment]
You can find it in the releases section on this GitHub (as ZIP) right now, or when it's accepted by Kodi, it will update automatically within Kodi. This will probably happen on a few days.

**Comment by cometoluc** [comment]
Hello MichaelArnauts ,

thanks for the answer, so i think that i can better wait until it is kodi and let it update by itself. Because i cannot find the releases in github. Is it possible to notify and put the link where it is released please. I really searched

**Comment by michaelarnauts** [comment]
> Is it possible to notify and put the link where it is released please. I really searched

https://github.com/add-ons/plugin.video.vtm.go/releases

**Comment by cometoluc** [comment]
Thanks, i found it but i will wait for a few days if it is resolved by the vtmgo update ( is that not the best i can do, otherwise i have to give in those codes on that link i suppose )

**Pull request merged**
