### PR TITLE
Fix VTM GO authentication

### PR DESCRIPTION
**Pull request by mediaminister**
This fixes https://github.com/add-ons/plugin.video.vtm.go/issues/223

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Wait, what. They broke auth again? The status CI should have picked that up :(

**Comment by mediaminister** [comment]
Status tests are skipped in this repo. Maybe a problem with the Github secrets?

**Comment by michaelarnauts** [comment]
Not sure, they are working for the unittests. I'll look into this today and push a release, but are we sure that the other changes have been tested completely?

**Comment by mediaminister** [comment]
I'll check, my repo is configured properly to run all tests.

**Pull request merged**
